[package]
name = "piper-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
espeak-rs = { path = "crates/espeak-rs" }
sonic-sys = {path = "crates/sonic-sys"}
ndarray = "0.16.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.89"
ort = {version = "2.0.0-rc.1"}
once_cell = "1.18.0"
riff-wave = "0.1.3"
flume = { version = "0.11.0", default-features = false, features = ["async"] }
rayon = { version = "1.8.1" }

[dev-dependencies]
ort = "2.0.0-rc.1"
rodio = "0.19.0"

